version: '3.8'

services:
  app:
    image: node:22
    working_dir: /usr/src/app
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
    command: sh -c "npm install && npm start"
    expose:
      - "3000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  mongo-data: 