version: '3.8'

services:
  app:
    image: node:22
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: sh -c "npm install && npm start"
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env

volumes:
  mongo-data: 